In [2]:
#imports
import polars as pl
import json

import requests
from deepface import DeepFace
from tqdm import tqdm

In [28]:
path=r'C:\Users\Porter\Desktop\jcp\merge_data\jcpst-sessions-2026-04-21-17-27-55.json'

In [33]:
import json

with open(path, "r", encoding="utf-8") as f:
    obj = json.load(f)

sessions = pl.DataFrame(obj["sessions"])

In [31]:
def expand_struct(df, colname):
    return df.with_columns(
        pl.col(colname).struct.unnest()
    )


#for treatment cols
def expand_list_struct_drop_inner(df: pl.DataFrame, col: str) -> pl.DataFrame:
    exploded = df.explode(col)

    inner_names = [f.name for f in exploded.schema[col].fields]
    outer_names = set(exploded.columns) - {col}

    keep_inner = [name for name in inner_names if name not in outer_names]

    return (
        exploded
        .with_columns(
            pl.struct(
                [pl.col(col).struct.field(name).alias(name) for name in keep_inner]
            ).alias(col)
        )
        .unnest(col)
    )


# def expand_list_struct_drop_inner(df: pl.DataFrame, col: str) -> pl.DataFrame:
#     exploded = df.explode(col)

#     inner_names = [f.name for f in exploded.schema[col].fields]
#     outer_names = set(exploded.columns) - {col}

#     keep_inner = [name for name in inner_names if name not in outer_names]

#     return (
#         exploded
#         .with_columns(
#             pl.struct(
#                 [pl.col(col).struct.field(name).alias(name) for name in keep_inner]
#             ).alias(col)
#         )
#         .unnest(col)
#     )

In [34]:
sessions=expand_struct(sessions,'session')

In [35]:
sessions=expand_list_struct_drop_inner(sessions,'linkedin_rows')

In [36]:
sessions=expand_struct(sessions,'profile_data')

In [37]:
sessions=expand_list_struct_drop_inner(sessions,'job_survey_rows')

In [40]:
sessions=sessions.select(pl.exclude(['session','profile_data']))

In [42]:
sessions=sessions.with_columns((pl.col("session_id") + "-" + pl.col("survey_id").fill_null('')).alias("session_survey_id"))

    # assert if it is a unique key
assert sessions.select(pl.col("session_survey_id").is_unique().all()).item()

In [43]:
sessions

shape: (6_379, 62)
┌───────────────┬──────┬──────┬───────────┬───┬────────────┬─────────────┬─────────┬───────────────┐
│ pageviews     ┆ ip   ┆ date ┆ survey_id ┆ … ┆ given_name ┆ family_name ┆ picture ┆ session_surve │
│ ---           ┆ ---  ┆ ---  ┆ ---       ┆   ┆ ---        ┆ ---         ┆ ---     ┆ y_id          │
│ list[struct[1 ┆ str  ┆ str  ┆ str       ┆   ┆ str        ┆ str         ┆ str     ┆ ---           │
│ 5]]           ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ str           │
╞═══════════════╪══════╪══════╪═══════════╪═══╪════════════╪═════════════╪═════════╪═══════════════╡
│ []            ┆ null ┆ null ┆ null      ┆ … ┆ null       ┆ null        ┆ null    ┆ f7fa559b9f7a2 │
│               ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ c799c18ad9fdd │
│               ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 9870…         │
│ []            ┆ null ┆ null ┆ null      ┆ … ┆ null       ┆ null        ┆ null    ┆ 3f26cb091ef56 │
│               ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 285e731e139ad │
│               ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ fff1…         │
│ []            ┆ null ┆ null ┆ null      ┆ … ┆ null       ┆ null        ┆ null    ┆ a590626c17454 │
│               ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ f9d94ff3cc4ce │
│               ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 1d22…         │
│ []            ┆ null ┆ null ┆ null      ┆ … ┆ null       ┆ null        ┆ null    ┆ ef9404ed9cfa5 │
│               ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 8957d5744c3d3 │
│               ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 2ac4…         │
│ []            ┆ null ┆ null ┆ null      ┆ … ┆ null       ┆ null        ┆ null    ┆ 66f836eb11d4d │
│               ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 192e072fc5ef0 │
│               ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 602e…         │
│ …             ┆ …    ┆ …    ┆ …         ┆ … ┆ …          ┆ …           ┆ …       ┆ …             │
│ [{5,"f4a71e7b ┆ null ┆ null ┆ null      ┆ … ┆ null       ┆ null        ┆ null    ┆ f4a71e7b41121 │
│ 411212092c565 ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 2092c5650e0cb │
│ 0e0c…         ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ d90a…         │
│ [{4,"b4ee3085 ┆ null ┆ null ┆ null      ┆ … ┆ null       ┆ null        ┆ null    ┆ b4ee3085efa7b │
│ efa7bea10317c ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ ea10317c6d4f4 │
│ 6d4f…         ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ a870…         │
│ [{3,"23dee37a ┆ null ┆ null ┆ null      ┆ … ┆ null       ┆ null        ┆ null    ┆ 23dee37ac713a │
│ c713a9809a23f ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 9809a23f09e43 │
│ 09e4…         ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ e6fc…         │
│ [{2,"cf347ddb ┆ null ┆ null ┆ null      ┆ … ┆ null       ┆ null        ┆ null    ┆ cf347ddb7664d │
│ 7664d7024316c ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 7024316c77f0c │
│ 77f0…         ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ c008…         │
│ [{1,"06e76df8 ┆ null ┆ null ┆ null      ┆ … ┆ null       ┆ null        ┆ null    ┆ 06e76df840e88 │
│ 40e88467544a5 ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 467544a50dfe1 │
│ 0dfe…         ┆      ┆      ┆           ┆   ┆            ┆             ┆         ┆ 0bfb…         │
└───────────────┴──────┴──────┴───────────┴───┴────────────┴─────────────┴─────────┴───────────────┘

In [44]:
signed_in=sessions.filter(pl.col('user_id').is_not_null())
signed_in

shape: (124, 62)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ pageviews ┆ ip        ┆ date      ┆ survey_id ┆ … ┆ given_nam ┆ family_na ┆ picture   ┆ session_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ me        ┆ ---       ┆ survey_i │
│ list[stru ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ d        │
│ ct[15]]   ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ [{2038,"1 ┆ 128.187.1 ┆ 2026-04-2 ┆ 868042633 ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ 1295f2d4 │
│ 295f2d4cf ┆ 16.32     ┆ 1         ┆ 1         ┆   ┆           ┆           ┆ edia.licd ┆ cfb3d6de │
│ b3d6ded84 ┆           ┆ 04:49:16  ┆           ┆   ┆           ┆           ┆ n.com/dms ┆ d8462211 │
│ 622…      ┆           ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ ed26e6…  │
│ [{2038,"1 ┆ 128.187.1 ┆ 2026-04-2 ┆ 375011837 ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ 1295f2d4 │
│ 295f2d4cf ┆ 16.32     ┆ 1         ┆ 8         ┆   ┆           ┆           ┆ edia.licd ┆ cfb3d6de │
│ b3d6ded84 ┆           ┆ 05:26:11  ┆           ┆   ┆           ┆           ┆ n.com/dms ┆ d8462211 │
│ 622…      ┆           ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ ed26e6…  │
│ [{2004,"6 ┆ 128.187.1 ┆ 2026-04-2 ┆ 430753952 ┆ … ┆ Shark     ┆ Frisbee   ┆ https://m ┆ 6246bc55 │
│ 246bc551e ┆ 16.32     ┆ 0         ┆ 8         ┆   ┆           ┆           ┆ edia.licd ┆ 1ea08318 │
│ a08318250 ┆           ┆ 11:05:41  ┆           ┆   ┆           ┆           ┆ n.com/dms ┆ 250c4a16 │
│ c4a…      ┆           ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ dba938…  │
│ [{2004,"6 ┆ 128.187.1 ┆ 2026-04-2 ┆ 224507788 ┆ … ┆ Shark     ┆ Frisbee   ┆ https://m ┆ 6246bc55 │
│ 246bc551e ┆ 16.32     ┆ 0         ┆ 3         ┆   ┆           ┆           ┆ edia.licd ┆ 1ea08318 │
│ a08318250 ┆           ┆ 11:16:38  ┆           ┆   ┆           ┆           ┆ n.com/dms ┆ 250c4a16 │
│ c4a…      ┆           ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ dba938…  │
│ [{1996,"1 ┆ null      ┆ null      ┆ null      ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ 1d446cb3 │
│ d446cb3d7 ┆           ┆           ┆           ┆   ┆           ┆           ┆ edia.licd ┆ d7ce5be0 │
│ ce5be0946 ┆           ┆           ┆           ┆   ┆           ┆           ┆ n.com/dms ┆ 946ea56e │
│ ea5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ c38938…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ [{98,"2fd ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 2fd4dfa6 │
│ 4dfa697e4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 97e4988a │
│ 988ab1452 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ b1452ef9 │
│ ef9…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f5cf62…  │
│ [{80,"140 ┆ null      ┆ null      ┆ null      ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ 14047fcd │
│ 47fcdfbcf ┆           ┆           ┆           ┆   ┆           ┆           ┆ edia.licd ┆ fbcfaf8a │
│ af8ab6d5a ┆           ┆           ┆           ┆   ┆           ┆           ┆ n.com/dms ┆ b6d5a3a7 │
│ 3a7…      ┆           ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 22982d…  │
│ [{69,"4bb ┆ null      ┆ null      ┆ null      ┆ … ┆ Tanner    ┆ Eastmond  ┆ https://m ┆ 4bb30d94 │
│ 30d94c79b ┆           ┆           ┆           ┆   ┆           ┆           ┆ edia.licd ┆ c79b3403 │
│ 34031c86b ┆           ┆           ┆           ┆   ┆           ┆           ┆ n.com/dms ┆ 1c86b825 │
│ 825…      ┆           ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 307450…  │
│ [{12,"b74 ┆ null      ┆ null      ┆ null      ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ b74f2ee8 │
│ f2ee8451d ┆           ┆           ┆           ┆   ┆           ┆           ┆ edia.licd ┆ 451dcd23 │
│ cd232b9bb ┆           ┆           ┆           ┆   ┆           ┆           ┆ n.com/dms ┆ 2b9bb12e │
│ 12e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 4e034b…  │
│ [{7,"dae7 ┆ null      ┆ null      ┆ null      ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ dae78823 │
│ 8823c8a09 ┆           ┆           ┆           ┆   ┆           ┆           ┆ edia.licd ┆ c8a09261 │
│ 2611ec8d6 ┆           ┆           ┆           ┆   ┆           ┆           ┆ n.com/dms ┆ 1ec8d6cc │
│ cce…      ┆           ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ eb2df6…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [45]:
signed_in_detail=signed_in.select(['given_name','family_name','picture']).filter(pl.col('given_name').is_not_null())
signed_in_detail=signed_in_detail.unique()
signed_in_detail

picture_link_list=signed_in_detail['picture'].to_list()

In [47]:
rows = []

for link in tqdm(picture_link_list):
    row = {
        "picture": link,

        "df_age": None,
        "df_face_confidence": None,
        "df_dominant_gender": None,
        "df_dominant_race": None,

        "df_prob_male": None,
        "df_prob_female": None,

        "df_prob_white": None,
        "df_prob_black": None,
        "df_prob_asian": None,
        "df_prob_indian": None,
        "df_prob_middle_eastern": None,
        "df_prob_latino": None,

        "df_status": None,
        "df_error": None,
    }

    try:
        img_data = requests.get(link, timeout=20).content

        with open("temp.jpg", "wb") as f:
            f.write(img_data)

        result = DeepFace.analyze(
            img_path="temp.jpg",
            actions=["age", "gender", "race"],
            enforce_detection=True
        )

        face = result[0]

        row["df_age"] = face.get("age")
        row["df_face_confidence"] = face.get("face_confidence")
        row["df_dominant_gender"] = face.get("dominant_gender")
        row["df_dominant_race"] = face.get("dominant_race")

        gender_dict = face.get("gender", {})
        race_dict = face.get("race", {})

        row["df_prob_male"] = float(gender_dict["Man"]) if "Man" in gender_dict else None
        row["df_prob_female"] = float(gender_dict["Woman"]) if "Woman" in gender_dict else None

        row["df_prob_white"] = float(race_dict["white"]) if "white" in race_dict else None
        row["df_prob_black"] = float(race_dict["black"]) if "black" in race_dict else None
        row["df_prob_asian"] = float(race_dict["asian"]) if "asian" in race_dict else None
        row["df_prob_indian"] = float(race_dict["indian"]) if "indian" in race_dict else None
        row["df_prob_middle_eastern"] = float(race_dict["middle eastern"]) if "middle eastern" in race_dict else None
        row["df_prob_latino"] = float(race_dict["latino hispanic"]) if "latino hispanic" in race_dict else None

        row["df_status"] = "ok"

    except Exception as e:
        msg = str(e)

        if "Face could not be detected" in msg:
            row["df_status"] = "no_face_detected"
        else:
            row["df_status"] = "error"

        row["df_error"] = msg

    rows.append(row)

pic_df = pl.DataFrame(rows)

pic_df

Action: race: 100%|██████████| 3/3 [00:00<00:00,  5.12it/s]
Action: race: 100%|██████████| 3/3 [00:00<00:00,  5.07it/s]
Action: race: 100%|██████████| 3/3 [00:00<00:00,  5.74it/s]
100%|██████████| 4/4 [00:03<00:00,  1.20it/s]

shape: (4, 15)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ picture    ┆ df_age ┆ df_face_co ┆ df_domina ┆ … ┆ df_prob_m ┆ df_prob_l ┆ df_status ┆ df_error  │
│ ---        ┆ ---    ┆ nfidence   ┆ nt_gender ┆   ┆ iddle_eas ┆ atino     ┆ ---       ┆ ---       │
│ str        ┆ i64    ┆ ---        ┆ ---       ┆   ┆ tern      ┆ ---       ┆ str       ┆ str       │
│            ┆        ┆ f64        ┆ str       ┆   ┆ ---       ┆ f64       ┆           ┆           │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ https://me ┆ 25     ┆ 0.92       ┆ Man       ┆ … ┆ 2.819904  ┆ 2.280221  ┆ ok        ┆ null      │
│ dia.licdn. ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ com/dms/im ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ https://me ┆ 23     ┆ 0.92       ┆ Man       ┆ … ┆ 13.370648 ┆ 15.566208 ┆ ok        ┆ null      │
│ dia.licdn. ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ com/dms/im ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ https://me ┆ 32     ┆ 0.9        ┆ Man       ┆ … ┆ 1.036455  ┆ 0.567853  ┆ ok        ┆ null      │
│ dia.licdn. ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ com/dms/im ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ https://me ┆ null   ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ no_face_d ┆ Face      │
│ dia.licdn. ┆        ┆            ┆           ┆   ┆           ┆           ┆ etected   ┆ could not │
│ com/dms/im ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ be        │
│ …          ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ detected  │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ in …      │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [50]:
import polars as pl
import pandas as pd
import gender_guesser.detector as gender
from ethnicolr import pred_fl_reg_name

d = gender.Detector(case_sensitive=False)

rows = []

for row in signed_in_detail.iter_rows(named=True):
    first_name = row["given_name"]
    last_name = row["family_name"]

    # gender-guesser
    gender_guess = d.get_gender(first_name) if first_name is not None else None

    temp_df = pd.DataFrame({
        "first_name": [first_name],
        "last_name": [last_name]
    })

    try:
        result = pred_fl_reg_name(temp_df, "last_name", "first_name")
        r = result.iloc[0]

        rows.append({
            "given_name": first_name,
            "family_name": last_name,

            # gender-guesser output
            "gg_gender_label": gender_guess,

            # ethnicolr output
            "eth_asian": r.get("asian"),
            "eth_hispanic": r.get("hispanic"),
            "eth_nh_black": r.get("nh_black"),
            "eth_nh_white": r.get("nh_white"),
            "eth_race_label": r.get("race"),
            "eth_processing_status": r.get("processing_status"),

            "ethnicolr_status": "ok"
        })

    except Exception as e:
        rows.append({
            "given_name": first_name,
            "family_name": last_name,

            "gg_gender_label": gender_guess,

            "eth_asian": None,
            "eth_hispanic": None,
            "eth_nh_black": None,
            "eth_nh_white": None,
            "eth_race_label": None,
            "eth_processing_status": None,

            "ethnicolr_status": f"error: {str(e)}"
        })

ethnicolr_gender_df = pl.DataFrame(rows)

ethnicolr_gender_df

2026-04-21 11:37:40,047 - INFO - Processing 1 full names
2026-04-21 11:37:40,087 - INFO - Applying Florida voter name model to 1 processable names (confidence interval: 1.0)
2026-04-21 11:37:40,089 - INFO - Data filtering summary: 1 → 1 rows (kept 100.0%)
2026-04-21 11:37:40,550 - INFO - Successfully predicted 1 of 1 names (100.0%)
2026-04-21 11:37:40,551 - INFO - Added columns: name_normalized_clean, nh_black, asian, __name, name_normalized, race, processing_status, nh_white, hispanic
2026-04-21 11:37:40,553 - INFO - Processing 1 full names
2026-04-21 11:37:40,556 - INFO - Applying Florida voter name model to 1 processable names (confidence interval: 1.0)
2026-04-21 11:37:40,558 - INFO - Data filtering summary: 1 → 1 rows (kept 100.0%)
2026-04-21 11:37:40,712 - INFO - Successfully predicted 1 of 1 names (100.0%)
2026-04-21 11:37:40,713 - INFO - Added columns: name_normalized_clean, nh_black, asian, __name, name_normalized, race, processing_status, nh_white, hispanic
2026-04-21 11:37:40,715 - INFO - Processing 1 full names
2026-04-21 11:37:40,720 - INFO - Applying Florida voter name model to 1 processable names (confidence interval: 1.0)
2026-04-21 11:37:40,721 - INFO - Data filtering summary: 1 → 1 rows (kept 100.0%)
2026-04-21 11:37:40,878 - INFO - Successfully predicted 1 of 1 names (100.0%)
2026-04-21 11:37:40,879 - INFO - Added columns: name_normalized_clean, nh_black, asian, __name, name_normalized, race, processing_status, nh_white, hispanic
2026-04-21 11:37:40,881 - INFO - Processing 1 full names
2026-04-21 11:37:40,886 - INFO - Applying Florida voter name model to 1 processable names (confidence interval: 1.0)
2026-04-21 11:37:40,887 - INFO - Data filtering summary: 1 → 1 rows (kept 100.0%)
2026-04-21 11:37:41,039 - INFO - Successfully predicted 1 of 1 names (100.0%)
2026-04-21 11:37:41,040 - INFO - Added columns: name_normalized_clean, nh_black, asian, __name, name_normalized, race, processing_status, nh_white, hispanic

shape: (4, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ given_nam ┆ family_na ┆ gg_gender ┆ eth_asian ┆ … ┆ eth_nh_wh ┆ eth_race_ ┆ eth_proce ┆ ethnicol │
│ e         ┆ me        ┆ _label    ┆ ---       ┆   ┆ ite       ┆ label     ┆ ssing_sta ┆ r_status │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ tus       ┆ ---      │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Porter    ┆ Olson     ┆ male      ┆ 0.000641  ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok       │
│ Spencer   ┆ Bailey    ┆ male      ┆ 0.003404  ┆ … ┆ 0.851664  ┆ nh_white  ┆ processed ┆ ok       │
│ Tanner    ┆ Eastmond  ┆ male      ┆ 0.0021    ┆ … ┆ 0.868747  ┆ nh_white  ┆ processed ┆ ok       │
│ Shark     ┆ Frisbee   ┆ unknown   ┆ 0.001475  ┆ … ┆ 0.950148  ┆ nh_white  ┆ processed ┆ ok       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [48]:
sessions=sessions.join(pic_df, on=['picture'],how='left')

In [51]:
sessions=sessions.join(ethnicolr_gender_df,on=['given_name','family_name'])

In [52]:
sessions

shape: (64, 84)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ pageviews ┆ ip        ┆ date      ┆ survey_id ┆ … ┆ eth_nh_wh ┆ eth_race_ ┆ eth_proce ┆ ethnicol │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ite       ┆ label     ┆ ssing_sta ┆ r_status │
│ list[stru ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ tus       ┆ ---      │
│ ct[15]]   ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ [{2038,"1 ┆ 128.187.1 ┆ 2026-04-2 ┆ 868042633 ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok       │
│ 295f2d4cf ┆ 16.32     ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ b3d6ded84 ┆           ┆ 04:49:16  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 622…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [{2038,"1 ┆ 128.187.1 ┆ 2026-04-2 ┆ 375011837 ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok       │
│ 295f2d4cf ┆ 16.32     ┆ 1         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ b3d6ded84 ┆           ┆ 05:26:11  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 622…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [{2004,"6 ┆ 128.187.1 ┆ 2026-04-2 ┆ 430753952 ┆ … ┆ 0.950148  ┆ nh_white  ┆ processed ┆ ok       │
│ 246bc551e ┆ 16.32     ┆ 0         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ a08318250 ┆           ┆ 11:05:41  ┆           ┆   ┆           ┆           ┆           ┆          │
│ c4a…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [{2004,"6 ┆ 128.187.1 ┆ 2026-04-2 ┆ 224507788 ┆ … ┆ 0.950148  ┆ nh_white  ┆ processed ┆ ok       │
│ 246bc551e ┆ 16.32     ┆ 0         ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ a08318250 ┆           ┆ 11:16:38  ┆           ┆   ┆           ┆           ┆           ┆          │
│ c4a…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [{1996,"1 ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok       │
│ d446cb3d7 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ce5be0946 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ea5…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ [{103,"52 ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.851664  ┆ nh_white  ┆ processed ┆ ok       │
│ b2dcdd526 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ f84658652 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c8d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [{80,"140 ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok       │
│ 47fcdfbcf ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ af8ab6d5a ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3a7…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [{69,"4bb ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.868747  ┆ nh_white  ┆ processed ┆ ok       │
│ 30d94c79b ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 34031c86b ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 825…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [{12,"b74 ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok       │
│ f2ee8451d ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cd232b9bb ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 12e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [{7,"dae7 ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok       │
│ 8823c8a09 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2611ec8d6 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cce…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘