In [38]:
#imports
import polars as pl
import json

import requests
from deepface import DeepFace
from tqdm import tqdm

In [39]:
session_path = r'C:\Users\Porter\Desktop\jcp\merge_data\jcpst-sessions-2026-04-07-22-48-30.json'

In [40]:
linkedin_path=r'C:\Users\Porter\Desktop\jcp\merge_data\linkedin-member-data-2026-04-07-224846.json'

In [41]:
import json

with open(linkedin_path, "r", encoding="utf-8") as f:
    obj = json.load(f)

linkedin = pl.DataFrame(obj)

In [42]:
import json
import polars as pl

path = r'C:\Users\Porter\Desktop\jcp\merge_data\jcpst-sessions-2026-04-07-22-48-30.json'

with open(path, "r", encoding="utf-8") as f:
    obj = json.load(f)

sessions = pl.DataFrame(obj["sessions"])

In [43]:

#for the linkedin cols
def expand_struct(df, colname):
    return df.with_columns(
        pl.col(colname).struct.unnest()
    )

#for treatment cols
def expand_list_struct_drop_inner(df: pl.DataFrame, col: str) -> pl.DataFrame:
    exploded = df.explode(col)

    inner_names = [f.name for f in exploded.schema[col].fields]
    outer_names = set(exploded.columns) - {col}

    keep_inner = [name for name in inner_names if name not in outer_names]

    return (
        exploded
        .with_columns(
            pl.struct(
                [pl.col(col).struct.field(name).alias(name) for name in keep_inner]
            ).alias(col)
        )
        .unnest(col)
    )

def merge_user_data(linkedin,sessions):
    #load the sessions json
    with open(sessions, "r", encoding="utf-8") as f:
        obj = json.load(f)

    sessions_df = pl.DataFrame(obj["sessions"])
    #load the linkedin json
    with open(linkedin, "r", encoding="utf-8") as f:
        obj = json.load(f)

    linkedin_df = pl.DataFrame(obj)
     #rename user-id so it matches the session schema, also rename other vars for clarity
    linkedin_df=linkedin_df.rename({'wordpress_user_id':'user_id',"last_synced_at":'account_last_synced_at','token_expires_at':'linkedin_token_expires_at','ip_history':'linkedin_ip_history','profile_data':'linkedin_profile_data'})
    linkedin_df=linkedin_df.with_columns(pl.col('user_id').cast(pl.Utf8).alias('user_id')) #cast to a string
    linkedin_df=linkedin_df.select(pl.exclude('wordpress_display_name')) #this column is redundant
    

    merged=sessions_df.join(linkedin_df,on=['user_id'],how='left')

    #expand the struct cols
    merged_expand = expand_struct(merged, "linkedin_profile_data")
    merged_expand = expand_list_struct_drop_inner(merged_expand, "treatment_snapshot")

    #make a unique key
    merged_expand = merged_expand.with_columns((pl.col("session_id") + "-" + pl.col("survey_id").fill_null('')).alias("session_survey_id"))

    # assert if it is a unique key
    assert merged_expand.select(pl.col("session_survey_id").is_unique().all()).item()

    return merged_expand

In [44]:
merged=merge_user_data(linkedin=linkedin_path,sessions=session_path)
merged

shape: (817, 40)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ session_id ┆ user_id ┆ user_disp ┆ session_s ┆ … ┆ given_nam ┆ family_na ┆ picture   ┆ session_s │
│ ---        ┆ ---     ┆ lay_name  ┆ tart      ┆   ┆ e         ┆ me        ┆ ---       ┆ urvey_id  │
│ str        ┆ str     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│            ┆         ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆           ┆ str       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3aa8ba57db ┆ null    ┆           ┆ 2026-04-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ 3aa8ba57d │
│ 3a60757ddc ┆         ┆           ┆ 7         ┆   ┆           ┆           ┆           ┆ b3a60757d │
│ 1e1e875b3c ┆         ┆           ┆ 22:47:17  ┆   ┆           ┆           ┆           ┆ dc1e1e875 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ b3c…      │
│ 0433769e92 ┆ 6       ┆ Porter    ┆ 2026-04-0 ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ 0433769e9 │
│ 2c7b83be73 ┆         ┆ Olson     ┆ 7         ┆   ┆           ┆           ┆ edia.licd ┆ 22c7b83be │
│ 156ce3ad77 ┆         ┆           ┆ 22:42:20  ┆   ┆           ┆           ┆ n.com/dms ┆ 73156ce3a │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ d77…      │
│ 0433769e92 ┆ 6       ┆ Porter    ┆ 2026-04-0 ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ 0433769e9 │
│ 2c7b83be73 ┆         ┆ Olson     ┆ 7         ┆   ┆           ┆           ┆ edia.licd ┆ 22c7b83be │
│ 156ce3ad77 ┆         ┆           ┆ 22:42:20  ┆   ┆           ┆           ┆ n.com/dms ┆ 73156ce3a │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ d77…      │
│ 1a551a87a2 ┆ 8       ┆ Shark     ┆ 2026-04-0 ┆ … ┆ Shark     ┆ Frisbee   ┆ https://m ┆ 1a551a87a │
│ eecb9c8060 ┆         ┆ Frisbee   ┆ 7         ┆   ┆           ┆           ┆ edia.licd ┆ 2eecb9c80 │
│ 5fef06739f ┆         ┆           ┆ 22:41:54  ┆   ┆           ┆           ┆ n.com/dms ┆ 605fef067 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 39f…      │
│ 07e35c2e68 ┆ 8       ┆ Shark     ┆ 2026-04-0 ┆ … ┆ Shark     ┆ Frisbee   ┆ https://m ┆ 07e35c2e6 │
│ b7a3396be9 ┆         ┆ Frisbee   ┆ 7         ┆   ┆           ┆           ┆ edia.licd ┆ 8b7a3396b │
│ 2b39219046 ┆         ┆           ┆ 22:38:36  ┆   ┆           ┆           ┆ n.com/dms ┆ e92b39219 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 046…      │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ f4a71e7b41 ┆ null    ┆           ┆ 2026-03-3 ┆ … ┆ null      ┆ null      ┆ null      ┆ f4a71e7b4 │
│ 1212092c56 ┆         ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆ 11212092c │
│ 50e0cbd90a ┆         ┆           ┆ 23:47:22  ┆   ┆           ┆           ┆           ┆ 5650e0cbd │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 90a…      │
│ b4ee3085ef ┆ null    ┆           ┆ 2026-03-3 ┆ … ┆ null      ┆ null      ┆ null      ┆ b4ee3085e │
│ a7bea10317 ┆         ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆ fa7bea103 │
│ c6d4f4a870 ┆         ┆           ┆ 23:47:19  ┆   ┆           ┆           ┆           ┆ 17c6d4f4a │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 870…      │
│ 23dee37ac7 ┆ null    ┆           ┆ 2026-03-3 ┆ … ┆ null      ┆ null      ┆ null      ┆ 23dee37ac │
│ 13a9809a23 ┆         ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆ 713a9809a │
│ f09e43e6fc ┆         ┆           ┆ 23:42:23  ┆   ┆           ┆           ┆           ┆ 23f09e43e │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6fc…      │
│ cf347ddb76 ┆ null    ┆           ┆ 2026-03-3 ┆ … ┆ null      ┆ null      ┆ null      ┆ cf347ddb7 │
│ 64d7024316 ┆         ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆ 664d70243 │
│ c77f0cc008 ┆         ┆           ┆ 23:40:32  ┆   ┆           ┆           ┆           ┆ 16c77f0cc │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 008…      │
│ 06e76df840 ┆ null    ┆           ┆ 2026-03-3 ┆ … ┆ null      ┆ null      ┆ null      ┆ 06e76df84 │
│ e88467544a ┆         ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆ 0e8846754 │
│ 50dfe10bfb ┆         ┆           ┆ 23:39:09  ┆   ┆           ┆           ┆           ┆ 4a50dfe10 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ bfb…      │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [45]:
signed_in=merged.filter(pl.col('user_id').is_not_null())
signed_in

shape: (67, 40)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ session_id ┆ user_id ┆ user_disp ┆ session_s ┆ … ┆ given_nam ┆ family_na ┆ picture   ┆ session_s │
│ ---        ┆ ---     ┆ lay_name  ┆ tart      ┆   ┆ e         ┆ me        ┆ ---       ┆ urvey_id  │
│ str        ┆ str     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│            ┆         ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆           ┆ str       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0433769e92 ┆ 6       ┆ Porter    ┆ 2026-04-0 ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ 0433769e9 │
│ 2c7b83be73 ┆         ┆ Olson     ┆ 7         ┆   ┆           ┆           ┆ edia.licd ┆ 22c7b83be │
│ 156ce3ad77 ┆         ┆           ┆ 22:42:20  ┆   ┆           ┆           ┆ n.com/dms ┆ 73156ce3a │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ d77…      │
│ 0433769e92 ┆ 6       ┆ Porter    ┆ 2026-04-0 ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ 0433769e9 │
│ 2c7b83be73 ┆         ┆ Olson     ┆ 7         ┆   ┆           ┆           ┆ edia.licd ┆ 22c7b83be │
│ 156ce3ad77 ┆         ┆           ┆ 22:42:20  ┆   ┆           ┆           ┆ n.com/dms ┆ 73156ce3a │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ d77…      │
│ 1a551a87a2 ┆ 8       ┆ Shark     ┆ 2026-04-0 ┆ … ┆ Shark     ┆ Frisbee   ┆ https://m ┆ 1a551a87a │
│ eecb9c8060 ┆         ┆ Frisbee   ┆ 7         ┆   ┆           ┆           ┆ edia.licd ┆ 2eecb9c80 │
│ 5fef06739f ┆         ┆           ┆ 22:41:54  ┆   ┆           ┆           ┆ n.com/dms ┆ 605fef067 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 39f…      │
│ 07e35c2e68 ┆ 8       ┆ Shark     ┆ 2026-04-0 ┆ … ┆ Shark     ┆ Frisbee   ┆ https://m ┆ 07e35c2e6 │
│ b7a3396be9 ┆         ┆ Frisbee   ┆ 7         ┆   ┆           ┆           ┆ edia.licd ┆ 8b7a3396b │
│ 2b39219046 ┆         ┆           ┆ 22:38:36  ┆   ┆           ┆           ┆ n.com/dms ┆ e92b39219 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 046…      │
│ 07e35c2e68 ┆ 8       ┆ Shark     ┆ 2026-04-0 ┆ … ┆ Shark     ┆ Frisbee   ┆ https://m ┆ 07e35c2e6 │
│ b7a3396be9 ┆         ┆ Frisbee   ┆ 7         ┆   ┆           ┆           ┆ edia.licd ┆ 8b7a3396b │
│ 2b39219046 ┆         ┆           ┆ 22:38:36  ┆   ┆           ┆           ┆ n.com/dms ┆ e92b39219 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 046…      │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2fd4dfa697 ┆ 3       ┆ Spencer   ┆ 2026-03-3 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2fd4dfa69 │
│ e4988ab145 ┆         ┆ Bailey    ┆ 1         ┆   ┆           ┆           ┆           ┆ 7e4988ab1 │
│ 2ef9f5cf62 ┆         ┆           ┆ 15:25:28  ┆   ┆           ┆           ┆           ┆ 452ef9f5c │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ f62…      │
│ 14047fcdfb ┆ 6       ┆ Porter    ┆ 2026-03-3 ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ 14047fcdf │
│ cfaf8ab6d5 ┆         ┆ Olson     ┆ 1         ┆   ┆           ┆           ┆ edia.licd ┆ bcfaf8ab6 │
│ a3a722982d ┆         ┆           ┆ 05:12:24  ┆   ┆           ┆           ┆ n.com/dms ┆ d5a3a7229 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 82d…      │
│ 4bb30d94c7 ┆ 2       ┆ Tanner    ┆ 2026-03-3 ┆ … ┆ Tanner    ┆ Eastmond  ┆ https://m ┆ 4bb30d94c │
│ 9b34031c86 ┆         ┆ Eastmond  ┆ 1         ┆   ┆           ┆           ┆ edia.licd ┆ 79b34031c │
│ b825307450 ┆         ┆           ┆ 04:26:26  ┆   ┆           ┆           ┆ n.com/dms ┆ 86b825307 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 450…      │
│ b74f2ee845 ┆ 6       ┆ Porter    ┆ 2026-03-3 ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ b74f2ee84 │
│ 1dcd232b9b ┆         ┆ Olson     ┆ 1         ┆   ┆           ┆           ┆ edia.licd ┆ 51dcd232b │
│ b12e4e034b ┆         ┆           ┆ 00:00:51  ┆   ┆           ┆           ┆ n.com/dms ┆ 9bb12e4e0 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ 34b…      │
│ dae78823c8 ┆ 6       ┆ Porter    ┆ 2026-03-3 ┆ … ┆ Porter    ┆ Olson     ┆ https://m ┆ dae78823c │
│ a092611ec8 ┆         ┆ Olson     ┆ 0         ┆   ┆           ┆           ┆ edia.licd ┆ 8a092611e │
│ d6cceb2df6 ┆         ┆           ┆ 23:49:39  ┆   ┆           ┆           ┆ n.com/dms ┆ c8d6cceb2 │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆ /im…      ┆ df6…      │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [46]:
signed_in_detail=signed_in.select(['given_name','family_name','picture']).filter(pl.col('given_name').is_not_null())
signed_in_detail=signed_in_detail.unique()
signed_in_detail

picture_link_list=signed_in_detail['picture'].to_list()

In [47]:
rows = []

for link in tqdm(picture_link_list):
    row = {
        "picture": link,

        "df_age": None,
        "df_face_confidence": None,
        "df_dominant_gender": None,
        "df_dominant_race": None,

        "df_prob_male": None,
        "df_prob_female": None,

        "df_prob_white": None,
        "df_prob_black": None,
        "df_prob_asian": None,
        "df_prob_indian": None,
        "df_prob_middle_eastern": None,
        "df_prob_latino": None,

        "df_status": None,
        "df_error": None,
    }

    try:
        img_data = requests.get(link, timeout=20).content

        with open("temp.jpg", "wb") as f:
            f.write(img_data)

        result = DeepFace.analyze(
            img_path="temp.jpg",
            actions=["age", "gender", "race"],
            enforce_detection=True
        )

        face = result[0]

        row["df_age"] = face.get("age")
        row["df_face_confidence"] = face.get("face_confidence")
        row["df_dominant_gender"] = face.get("dominant_gender")
        row["df_dominant_race"] = face.get("dominant_race")

        gender_dict = face.get("gender", {})
        race_dict = face.get("race", {})

        row["df_prob_male"] = float(gender_dict["Man"]) if "Man" in gender_dict else None
        row["df_prob_female"] = float(gender_dict["Woman"]) if "Woman" in gender_dict else None

        row["df_prob_white"] = float(race_dict["white"]) if "white" in race_dict else None
        row["df_prob_black"] = float(race_dict["black"]) if "black" in race_dict else None
        row["df_prob_asian"] = float(race_dict["asian"]) if "asian" in race_dict else None
        row["df_prob_indian"] = float(race_dict["indian"]) if "indian" in race_dict else None
        row["df_prob_middle_eastern"] = float(race_dict["middle eastern"]) if "middle eastern" in race_dict else None
        row["df_prob_latino"] = float(race_dict["latino hispanic"]) if "latino hispanic" in race_dict else None

        row["df_status"] = "ok"

    except Exception as e:
        msg = str(e)

        if "Face could not be detected" in msg:
            row["df_status"] = "no_face_detected"
        else:
            row["df_status"] = "error"

        row["df_error"] = msg

    rows.append(row)

pic_df = pl.DataFrame(rows)

pic_df

Action: race: 100%|██████████| 3/3 [00:00<00:00,  4.98it/s]
Action: race: 100%|██████████| 3/3 [00:00<00:00,  5.48it/s]
Action: race: 100%|██████████| 3/3 [00:00<00:00,  5.49it/s]
100%|██████████| 4/4 [00:03<00:00,  1.07it/s]

shape: (4, 15)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ picture    ┆ df_age ┆ df_face_co ┆ df_domina ┆ … ┆ df_prob_m ┆ df_prob_l ┆ df_status ┆ df_error  │
│ ---        ┆ ---    ┆ nfidence   ┆ nt_gender ┆   ┆ iddle_eas ┆ atino     ┆ ---       ┆ ---       │
│ str        ┆ i64    ┆ ---        ┆ ---       ┆   ┆ tern      ┆ ---       ┆ str       ┆ str       │
│            ┆        ┆ f64        ┆ str       ┆   ┆ ---       ┆ f64       ┆           ┆           │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ https://me ┆ null   ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ no_face_d ┆ Face      │
│ dia.licdn. ┆        ┆            ┆           ┆   ┆           ┆           ┆ etected   ┆ could not │
│ com/dms/im ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ be        │
│ …          ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ detected  │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ in …      │
│ https://me ┆ 23     ┆ 0.92       ┆ Man       ┆ … ┆ 13.370648 ┆ 15.566208 ┆ ok        ┆ null      │
│ dia.licdn. ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ com/dms/im ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ https://me ┆ 25     ┆ 0.92       ┆ Man       ┆ … ┆ 2.819904  ┆ 2.280221  ┆ ok        ┆ null      │
│ dia.licdn. ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ com/dms/im ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ https://me ┆ 32     ┆ 0.9        ┆ Man       ┆ … ┆ 1.036455  ┆ 0.567853  ┆ ok        ┆ null      │
│ dia.licdn. ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ com/dms/im ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [48]:
import polars as pl
import pandas as pd
import gender_guesser.detector as gender
from ethnicolr import pred_fl_reg_name

d = gender.Detector(case_sensitive=False)

rows = []

for row in signed_in_detail.iter_rows(named=True):
    first_name = row["given_name"]
    last_name = row["family_name"]

    # gender-guesser
    gender_guess = d.get_gender(first_name) if first_name is not None else None

    temp_df = pd.DataFrame({
        "first_name": [first_name],
        "last_name": [last_name]
    })

    try:
        result = pred_fl_reg_name(temp_df, "last_name", "first_name")
        r = result.iloc[0]

        rows.append({
            "given_name": first_name,
            "family_name": last_name,

            # gender-guesser output
            "gg_gender_label": gender_guess,

            # ethnicolr output
            "eth_asian": r.get("asian"),
            "eth_hispanic": r.get("hispanic"),
            "eth_nh_black": r.get("nh_black"),
            "eth_nh_white": r.get("nh_white"),
            "eth_race_label": r.get("race"),
            "eth_processing_status": r.get("processing_status"),

            "ethnicolr_status": "ok"
        })

    except Exception as e:
        rows.append({
            "given_name": first_name,
            "family_name": last_name,

            "gg_gender_label": gender_guess,

            "eth_asian": None,
            "eth_hispanic": None,
            "eth_nh_black": None,
            "eth_nh_white": None,
            "eth_race_label": None,
            "eth_processing_status": None,

            "ethnicolr_status": f"error: {str(e)}"
        })

ethnicolr_gender_df = pl.DataFrame(rows)

ethnicolr_gender_df

2026-04-07 21:31:12,437 - INFO - Processing 1 full names
2026-04-07 21:31:12,437 - INFO - Applying Florida voter name model to 1 processable names (confidence interval: 1.0)
2026-04-07 21:31:12,437 - INFO - Data filtering summary: 1 → 1 rows (kept 100.0%)
2026-04-07 21:31:12,552 - INFO - Successfully predicted 1 of 1 names (100.0%)
2026-04-07 21:31:12,552 - INFO - Added columns: name_normalized, __name, hispanic, race, nh_white, name_normalized_clean, nh_black, asian, processing_status
2026-04-07 21:31:12,557 - INFO - Processing 1 full names
2026-04-07 21:31:12,557 - INFO - Applying Florida voter name model to 1 processable names (confidence interval: 1.0)
2026-04-07 21:31:12,557 - INFO - Data filtering summary: 1 → 1 rows (kept 100.0%)
2026-04-07 21:31:12,678 - INFO - Successfully predicted 1 of 1 names (100.0%)
2026-04-07 21:31:12,678 - INFO - Added columns: name_normalized, __name, hispanic, race, nh_white, name_normalized_clean, nh_black, asian, processing_status
2026-04-07 21:31:12,681 - INFO - Processing 1 full names
2026-04-07 21:31:12,685 - INFO - Applying Florida voter name model to 1 processable names (confidence interval: 1.0)
2026-04-07 21:31:12,685 - INFO - Data filtering summary: 1 → 1 rows (kept 100.0%)
2026-04-07 21:31:12,833 - INFO - Successfully predicted 1 of 1 names (100.0%)
2026-04-07 21:31:12,833 - INFO - Added columns: name_normalized, __name, hispanic, race, nh_white, name_normalized_clean, nh_black, asian, processing_status
2026-04-07 21:31:12,835 - INFO - Processing 1 full names
2026-04-07 21:31:12,837 - INFO - Applying Florida voter name model to 1 processable names (confidence interval: 1.0)
2026-04-07 21:31:12,837 - INFO - Data filtering summary: 1 → 1 rows (kept 100.0%)
2026-04-07 21:31:12,937 - INFO - Successfully predicted 1 of 1 names (100.0%)
2026-04-07 21:31:12,937 - INFO - Added columns: name_normalized, __name, hispanic, race, nh_white, name_normalized_clean, nh_black, asian, processing_status

shape: (4, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ given_nam ┆ family_na ┆ gg_gender ┆ eth_asian ┆ … ┆ eth_nh_wh ┆ eth_race_ ┆ eth_proce ┆ ethnicol │
│ e         ┆ me        ┆ _label    ┆ ---       ┆   ┆ ite       ┆ label     ┆ ssing_sta ┆ r_status │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ tus       ┆ ---      │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Shark     ┆ Frisbee   ┆ unknown   ┆ 0.001475  ┆ … ┆ 0.950148  ┆ nh_white  ┆ processed ┆ ok       │
│ Spencer   ┆ Bailey    ┆ male      ┆ 0.003404  ┆ … ┆ 0.851664  ┆ nh_white  ┆ processed ┆ ok       │
│ Porter    ┆ Olson     ┆ male      ┆ 0.000641  ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok       │
│ Tanner    ┆ Eastmond  ┆ male      ┆ 0.0021    ┆ … ┆ 0.868747  ┆ nh_white  ┆ processed ┆ ok       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [49]:
merged=merged.join(pic_df, on=['picture'],how='left')

In [50]:
merged=merged.join(ethnicolr_gender_df,on=['given_name','family_name'])

In [51]:
merged

shape: (32, 62)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ session_id ┆ user_id ┆ user_disp ┆ session_s ┆ … ┆ eth_nh_wh ┆ eth_race_ ┆ eth_proce ┆ ethnicolr │
│ ---        ┆ ---     ┆ lay_name  ┆ tart      ┆   ┆ ite       ┆ label     ┆ ssing_sta ┆ _status   │
│ str        ┆ str     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ tus       ┆ ---       │
│            ┆         ┆ str       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ str       │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆ str       ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0433769e92 ┆ 6       ┆ Porter    ┆ 2026-04-0 ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok        │
│ 2c7b83be73 ┆         ┆ Olson     ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 156ce3ad77 ┆         ┆           ┆ 22:42:20  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0433769e92 ┆ 6       ┆ Porter    ┆ 2026-04-0 ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok        │
│ 2c7b83be73 ┆         ┆ Olson     ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 156ce3ad77 ┆         ┆           ┆ 22:42:20  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1a551a87a2 ┆ 8       ┆ Shark     ┆ 2026-04-0 ┆ … ┆ 0.950148  ┆ nh_white  ┆ processed ┆ ok        │
│ eecb9c8060 ┆         ┆ Frisbee   ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 5fef06739f ┆         ┆           ┆ 22:41:54  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 07e35c2e68 ┆ 8       ┆ Shark     ┆ 2026-04-0 ┆ … ┆ 0.950148  ┆ nh_white  ┆ processed ┆ ok        │
│ b7a3396be9 ┆         ┆ Frisbee   ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 2b39219046 ┆         ┆           ┆ 22:38:36  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 07e35c2e68 ┆ 8       ┆ Shark     ┆ 2026-04-0 ┆ … ┆ 0.950148  ┆ nh_white  ┆ processed ┆ ok        │
│ b7a3396be9 ┆         ┆ Frisbee   ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ 2b39219046 ┆         ┆           ┆ 22:38:36  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 52b2dcdd52 ┆ 7       ┆ Spencer   ┆ 2026-03-3 ┆ … ┆ 0.851664  ┆ nh_white  ┆ processed ┆ ok        │
│ 6f84658652 ┆         ┆ Bailey    ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ c8d26330e9 ┆         ┆           ┆ 16:16:23  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 14047fcdfb ┆ 6       ┆ Porter    ┆ 2026-03-3 ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok        │
│ cfaf8ab6d5 ┆         ┆ Olson     ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ a3a722982d ┆         ┆           ┆ 05:12:24  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 4bb30d94c7 ┆ 2       ┆ Tanner    ┆ 2026-03-3 ┆ … ┆ 0.868747  ┆ nh_white  ┆ processed ┆ ok        │
│ 9b34031c86 ┆         ┆ Eastmond  ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ b825307450 ┆         ┆           ┆ 04:26:26  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ b74f2ee845 ┆ 6       ┆ Porter    ┆ 2026-03-3 ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok        │
│ 1dcd232b9b ┆         ┆ Olson     ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ b12e4e034b ┆         ┆           ┆ 00:00:51  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ dae78823c8 ┆ 6       ┆ Porter    ┆ 2026-03-3 ┆ … ┆ 0.988427  ┆ nh_white  ┆ processed ┆ ok        │
│ a092611ec8 ┆         ┆ Olson     ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│ d6cceb2df6 ┆         ┆           ┆ 23:49:39  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘